version: '3'
services:
  opendaylight:
    image: glefevre/opendaylight
    container_name: opendaylight
    ports:
     - "6633:6633"
     - "8181:8181"
     - "8101:8101"
  mininet:
    image: iwaseyusuke/mininet
    container_name: mininet
    depends_on:
     - opendaylight
    tty: true
    privileged: true
    environment:
     - DISPLAY
     - XTERM
    volumes:
     - /tmp/.X11-unix:/tmp/.X11-unix
     - /lib/modules:/lib/modules
     - ./log:/root/log
     - ./Practica2_TTRC:/root/
